<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{cd576b26-1fdb-4b4f-8944-02a8451659e2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbLiquidTank : FB_Tank; 	

	bFillButton : BOOL;
	bDrainButton : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbLiquidTank(bIsFillButtonPressed := bFillButton, bIsDrainButtonPressed := bDrainButton);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>