<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{836900bc-2dad-494f-b411-7c4011f77035}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbActuation : FB_Actuation;
	bButtonPress : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbActuation(bActuation := bButtonPress);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>