<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{bbf0f65c-bc6c-4ce4-9543-ace892cd63cb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbSlicer : FB_Slicer;
	bStartButton : BOOL;
	fM1Position : LREAL;
	fM1sPosition : LREAL;
	fM2Position : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbSlicer(bStartButton := bStartButton,
		 fM1Position => fM1Position,
		 fM1sPosition => fM1sPosition,
		 fM2Position => fM2Position);]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="14" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>